### ISSUE TITLE
Images contained in tooltip not being loading when using plugin

### ISSUE THREAD

**Issue by mwhhorton1987** [FriendsOfShopware/FroshLazySizes#29]
### PHP Version

8.1.2

### Shopware Version

6.4.20.2

### Plugin Version

1.1.2

### Actual behaviour

When on the product listing, if the listing detail contains a tooltip that also contains a image example below

Tooltip Element 
![image](https://github.com/FriendsOfShopware/FroshLazySizes/assets/15687823/2a0ebed4-8657-4e53-b660-d48a1ef7dd7d)

Current Display
![image](https://github.com/FriendsOfShopware/FroshLazySizes/assets/15687823/12d3186a-0e28-44ab-b61b-944d2c2c6d99)

Dynamic Tooltip with no image
![image](https://github.com/FriendsOfShopware/FroshLazySizes/assets/15687823/7574d7a6-dc46-417d-9c2b-a6666766b712)

### Expected behaviour

Screenshot of the expect tooltip content on hover

![image](https://github.com/FriendsOfShopware/FroshLazySizes/assets/15687823/6f069adb-d3b4-4007-95f4-f08cebb74ffb)

Dynamic tooltip - Populated with image 
![image](https://github.com/FriendsOfShopware/FroshLazySizes/assets/15687823/4dccc57f-e904-4b87-9aa9-a9339016b886)

### Steps to Reproduce?

To reproduce you will need to install the Energy Saving Ordinance (EnEV) plugin from the Shopware store and assign the product a energy rating and energy label media (there tooltip image)

**Comment by tinect** [comment]
Hi @mwhhorton1987

I don't have the capacity to check support for any plugin, especially it is a paid one.

You are welcome to create a PR solving this issue or contact the plugin manufacturer.

**Comment by brandonmillar** [comment]
Hi @tinect + @mwhhorton1987 

I have spent some time investigating this. It appears the cause of the issue is in the below block. The "src" attribute is being set to the base64 string when tooltips are used, rather than the media URL, in [src/Resources/views/storefront/utilities/thumbnail-lazysize.html.twig](https://github.com/FriendsOfShopware/FroshLazySizes/blob/336e3fdbedc8fa6cbf97b7bfc55a3b61c96e444c/src/Resources/views/storefront/utilities/thumbnail-lazysize.html.twig#L50):
```
... 
{% block thumbnail_utility_img %}
        {% if src is not defined %}
            {% set src = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==' %}
        {% endif %}
....
```

Making a change to cater for this, such as the below resolves the tooltip issue we are seeing. However, my concern is, I am unsure if the base64 image fallback is to cater for specific scenarios, or if it is a generic fallback to ensure there is content in the src? Would the below amendment be a suitable fix?

```
...
    {% block thumbnail_utility_img %}
        {% if src is not defined %}
            {% if media is definied and media.url is defined %}
                {% set src = media.url|frosh_encode_url %}
            {% else %}
                {% set src = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==' %}
            {% endif %}
        {% endif %}
...
```
Following the above change on our staging environment, the tooltips are loading correctly and images are being lazy loaded.

If you agree with the change I will raise a pull request shortly.

Thankyou

**Comment by tinect** [comment]
This would kill the function of this plugin. What I mean: Uninstalling this plugin has the same effect on performance and disadvantages.

You might want to use this function deficated for the element the used plugins output:

https://github.com/FriendsOfShopware/FroshLazySizes?tab=readme-ov-file#selectively-deactivate-plugins-lazysizes-and-lazyloading-function

Contact the manufacturer or decorate its template setting the mentioned variable.
