### ISSUE TITLE
Remove lazy loading for the start image and the small preview images on product detail pages

### ISSUE THREAD

**Issue by gamerlion7** [FriendsOfShopware/FroshLazySizes#32]
### Actual behaviour

Images "above the fold" are lazy loaded.

### Expected behaviour

Images "above the fold" should not be lazy loaded, because it increases the page load time and Lighthouse complains.

It would be great to remove lazy loading for the start image and the small preview images on product detail pages.

### Steps to Reproduce?

Load and inspect a product detail page.

**Comment by tinect** [comment]
as mentioned in mail, this will not happen due to possible bad performance.
please use the classes mentioned in readme.

**Comment by tinect** [comment]
I forgot that the classes are just cms relevant (block and section)- not any div. Did you use the cms-things of shopware?
Try setting a variable `lazysizes ` with the value `false` any time before the thumbnail is embedded.
See also `specific images` in https://github.com/FriendsOfShopware/FroshLazySizes?tab=readme-ov-file#specific-images

This is no fix, but a feature. It is not "just simple" because you might have to think about many things:
- need for any shop?
- what are the disadvantages?
  - performance (twig and/or js) + image sizes with deactivating the benefits of this plugin
  - maintenance
  - idk

For the moment, I don't see this general feature for any shop coming from this plugin. This does not mean I will just discard this request or this will never come, but there are too many things we have to check before adding it. Therefore, please add this to your own project, if you see the need for you.

**Comment by gamerlion7** [comment]
Thank you for reopening this Issue.

I extended /src/Resources/views/storefront/element/cms-element-image-gallery.html.twig to add the classes to the divs that contain the start image and the small preview images on the product detail page.

I do not get what you mean. How else should it be done?

How can I add _lazysizes="false"_ to these images?

I think you misunderstood it. It should not deactivate the sizes function. Only lazy loading should be removed.

**Comment by tinect** [comment]
Just a heads-up: LazySizes relies on JavaScript, which only runs after the page is ready, so it will always apply some form of lazy loading.

Regarding your comment:

> I extended /src/Resources/views/storefront/element/cms-element-image-gallery.html.twig to add the classes to the divs that contain the start image and the small preview images on the product detail page.

In the Shopware Admin's CMS editor, you can set "CMS classes" directly.

Also, the variable should be set within Twig using `{% set lazysizes = false %}`.

**Comment by gamerlion7** [comment]
As I said: I think you misunderstood it. It should not deactivate the sizes function. Only lazy loading should be removed.

**Comment by tinect** [comment]
Okay, you read my message?

> Just a heads-up: LazySizes relies on JavaScript, which only runs after the page is ready, so it will always apply some form of lazy loading.

**Comment by gamerlion7** [comment]
If an image above the fold has _loading="lazy"_, the loading time is worse as without _loading="lazy"_: https://web.dev/articles/lcp-lazy-loading

JavaScript increases the loading time, but that is not the topic of this issue.

It would be great, if Shopware 6 just used correct values for the sizes attribute. That would be best for the loading times.

**Comment by tinect** [comment]
This is not the case of the used library, isn't it?
https://github.com/aFarkas/lazysizes?tab=readme-ov-file#how-to

> It would be great, if Shopware 6 just used correct values for the sizes attribute. That would be best for the loading times.

This was the reason, to create this plugin, while a PR would break the entire storefront and noexternal developer has energy to get it managed to be merged and released. But, you are free to fix it in your project, so you don't need such plugin.

**Comment by tinect** [comment]
Additionally, there is no attribute with `loading="lazy"` on default storefront or with this plugin, is there?

**Comment by gamerlion7** [comment]
The plugin does not use `loading="lazy"`. It uses the principle of lazy loading. Lighthouse and browsers recognise the same behaviour.

Images above the fold should not be lazy loaded. The browser wants to download the images, but the source code says "do not load them immediately". The browser calculates that the images are above the fold or nearby and then starts downloading them. The time for calculating the image position increases the loading time.

Shopware uses loading="lazy" for images in the frontend since 6.5.1.

So the lazy loading of the plugin can be removed for Shopware 6.5.1 and newer versions, if it is not already done.

The plugin uses the classes "lazyautosizes" and "lazyloaded". It seems like removing the class "lazyloaded" for the start image and the small preview images on product detail pages would fix this issue.

**Comment by tinect** [comment]
lazyloaded comes from used library lazysizes, not this plugin.

I don’t know why we talk past each other.

However, thank you for the detailed discussion on this topic. After reviewing the issue, it appears that the behavior you're experiencing isn't related to the LazySizes plugin itself, as it inherently relies on JavaScript to handle image loading. Additionally, the plugin doesn't add the `loading="lazy"` attribute or classes, so the issue seems to lie elsewhere. For your specific case, customizing this in your project might be the best approach.

**Comment by gamerlion7** [comment]
This plugin loads images lazy without using loading="lazy".

The issue is caused by the plugin.

Fixing false sizes attributes is good and loading images lazy that are a good way below the fold improves the page load time.
