### ISSUE TITLE
Image file names containing spaces will lead to srcset errors

### ISSUE THREAD

**Issue by 4BRobby** [FriendsOfShopware/FroshLazySizes#5]
### Shopware Version

6.4.18

### Actual behaviour

frosh_encode_url does not properly encode spaces in thumbnail file names.

Output of a file like 'my image.jpg' will lead to:
`data-srcset="{..}/media/{..}/my%20image.jpg {maxwidth}w, {..}/thumbnail/{..}/my image.jpg 1920w"`

When lazy loading javascript replaces srcset this will lead to the warning: "Failed parsing 'srcset' attribute value since it has an unknown descriptor."

### Expected behaviour

Output of a file like 'my image.jpg' will lead to:
`data-srcset="../my%20image.jpg {maxwidth}w, ../my%20image.jpg 1920w"`

### Steps to Reproduce?

Upload images with spaces.
Suggestion: why not use sw_encode_url filter instead? 
This was my quick solution in thumbnail.html.twig - replace frosh_encode_url  with sw_encode_url.

Investigation result, error reason:
- As thumbnails do not have a /media/ path part in this case (instead /thumbnail/) the frosh_encode_url function returns the plain url.

**Comment by tinect** [comment]
Hi,

Thank you for your message.

Background information: this plugin is an extraction of FroshPlatformThumbnailProcessor. That is the reason why here can be things implemented, which may not work. Your problem is one of this :-)
frosh_encode_url has been introduced to support special character, f.e. [to support imgproxy](https://github.com/FriendsOfShopware/FroshLazySizes/blob/0d331cc60e5acbad38a873af46350eff7069d220/src/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php#L33)

I'll check and fix it within the next days.

**Comment by 4BRobby** [comment]
Hi,
Saw the comment about imgproxy. In our case we just use a cdn, so no effect there.
In this case maybe it is better to use a preg_split with /media/ OR /thumbnail/ as splitter.

**Comment by 4BRobby** [comment]
Would love to contribute, yes.

**Comment by tinect** [comment]
Fixed with 1.0.1 and 2.0.1

**Comment by 4BRobby** [comment]
Thank you - I really had no time to put this in a fork.
